name: beamer
description: A routing package built on top of Router and Navigator's pages API, supporting arbitrary nested navigation, guards and more.
version: 2.0.0-dev.0
homepage: https://beamer.dev
repository: https://github.com/slovnicki/beamer/tree/master/package
issue_tracker: https://github.com/slovnicki/beamer/issues
topics:
  - beamer
  - router
  - navigator
funding:
  - https://github.com/sponsors/slovnicki

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  mocktail: ^0.3.0
